#+TITLE: Readme


* Тестовое задание Dr.Web
Необходимо разработать на C++17 утилиту для ОС Linux, предназначенную
для запуска исполняемых файлов и вывода информации об их выполнении.
Утилита должна принимать один аргумент командной строки: путь к директории.
При запуске утилита должна искать в указанной директории исполняемые
файлы, последовательно запускать их и для каждого файла выводить в
stdout строку вида:
код_завершения<символ_табуляции>имя_файла
Если при интерпретации аргумента командной строки или при работе
возникла ошибка, выводить в stderr сообщение об ошибке и завершаться с
кодом EXIT_FAILURE.
Завершение запускаемого файла по сигналу тажке следует трактовать как
ошибку и завершаться с EXIT_FAILURE.
При успешном окончании работы завершаться с кодом EXIT_SUCCESS.
Сигналы, отправляемые утилите, обрабатывать не нужно.
Разрешается использование любых open source библиотек.
** Note
- Используется один дочерний процесс.
** Тесты
1. Ровно один аргумент
2. Путь существует
3. Аргумент--- это дирректория
4. Пустая дирректория
5. Пустой не исполняемы файл
6. Не исполняемый файл
7. Пустой исполняемый файл
8. return 0
9. return 1
10. return -1
11. return 42
12. raise SIGINT
13. Вложенный дирректории
14. Вложенные дирректории, в промежуточных уровнях вложенности которых нет файлов
15. ВСЕ ВЫШЕПЕРЕЧИСЛЕННОЕ
